FROM openjdk:8-jre-slim

# Adding packages
RUN apt-get update -qq && apt-get install -qqy \
    apt-transport-https \
    ca-certificates \
    curl \
    lxc \
    iptables \
    software-properties-common && \

# Install Docker from Docker Inc. repositories.
RUN curl -sSL https://get.docker.com/ | sh

# Install the magic wrapper.
ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# Define additional metadata for our image.
VOLUME /var/lib/docker

# Install fog agent
RUN curl -s https://packagecloud.io/install/repositories/iofog/iofog/script.deb.sh | bash && \
    apt-get install iofog

# Start wrapper and fog-agent
CMD usr/local/bin/wrapdocker && java -jar /usr/bin/iofogd.jar start

