#!/bin/sh
### BEGIN INIT INFO
# Provides:          iofabric
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop iofabric server
### END INIT INFO

SERVICE_NAME=iofabric
PATH_TO_JAR=/usr/bin 
JAR_FILE_NAME=$PATH_TO_JAR/$SERVICE_NAME.jar

if [ "$(id -u)" != '0' ]; then
	log_failure_msg "$SERVICE_NAME must be run as root"
	exit 1
fi
case $1 in
    start)
	mv /dev/random /dev/random.real
	ln -s /dev/urandom /dev/random

	echo "Starting iofabric service..."
        cd $PATH_TO_JAR
        sudo java -jar $JAR_FILE_NAME start S &
    ;;
    stop)
        cd $PATH_TO_JAR
        sudo java -jar $JAR_FILE_NAME stop S
    ;;
 #   restart)
 #echo "Restarting iofabric service..."
 #   cd $PATH_TO_JAR
 #  sudo java -jar $JAR_FILE_NAME stop R
 # sudo java -jar $JAR_FILE_NAME start &
 #  ;;
esac


